dylan-lang/testworks

run.dylan
* run.dylan
(test-output): Call force-output to make sure output is visible
sooner rather than waiting for a buffer to flush.
=> Output progress text more frequently.

results.dylan
* results.dylan
(result-type-name on ``<benchmark-result>``): New method to provide
a reporting label for benchmark results.
=> testworks: Fix reporting support for benchmarks

command-line.dylan, tests/test-command-line.dylan
Using ``<choice-option>`` results in better error reporting.
* ``command-line.dylan``
(``general``): Move some constants to the top of the file before
they are used.
(``parse-args``): Switch from ``<optional-parameter-option>`` and
``<parameter-option>`` to ``<choice-option>``.
(``make-runner-from-command-line``): Remove extraneous error handling
now that ``<choice-option>`` is handling it.
* ``tests/test-command-line.dylan``
(``test-make-runner-from-command-line``): Remove test of bare ``--debug``
for now as it doesn't work any longer.
=> Use <choice-option> in command line parser.

command-line.dylan, documentation/users-guide/source/reference.rst, library.dylan, run.dylan, tests/specification.dylan
Sometimes test functions need to have information about external
entities, such as the directory path of test or reference data files, or
the hostname of a test database server. This commit allows this sort of
information to be supplied on the command line of the test application.
=> testworks: Support passing options to tests

run.dylan
* run.dylan
(execute-component): Just assign the value of the profiled expression
to cond rather than first setting cond to #f and then assigning
a new value to it.
=> Remove assignment, just use value of expression.

coloring.dylan, components.dylan, documentation/users-guide/source/reference.rst, documentation/users-guide/source/usage.rst, library.dylan, reports.dylan, results.dylan, run.dylan, tests/testworks-test-suite.dylan
It is useful to be able to note that a test is expected to fail
and to note when it unexpectedly succeeds.  This will be useful
for the Dylan test suites where we have some long-standing failures
that can be flagged as expecting to fail so that we will notice
new failures or other changes in the status of tests.
Fixes bug #72.
* components.dylan
(``%expected-failure?``): New slot on ``<runnable>``, parent class for
both ``<test>`` and ``<benchmark>``.
(``expected-failure?``): New method to see if a test is expected
to fail. This inspects ``%expected-failure?`` and evaluates the
method if there is one.
* results.dylan
(``$expected-failure``, ``$unexpected-success``): New status values.
(``<result-status>``): Update to include new status values.
(``status-name``): Update to handle new …
=> Add expected-failure support.

assertions.dylan, documentation/users-guide/source/reference.rst, documentation/users-guide/source/usage.rst, library.dylan, tests/specification.dylan, tests/testworks-test-suite.dylan
This brings ``assert-instance?`` and ``assert-not-instance?`` macros to the newer
assert-based macros. These can be used to get better test failure output
when an assertion fails (rather than ``assert-true(instance?(...))`` or
``assert-false(instance?(...))``).
* assertions.dylan
(``do-check-instance?``): Add ``negate?`` flag to handle ``~instance?`` as well.
(``check-instance?``): Pass ``#f`` for ``negate?`` to ``do-check-instance?``.
(``assert-instance?``, ``assert-not-instance?``): New macros.
* library.dylan
(module ``testworks``): Export ``assert-instance?``, ``assert-not-instance?``.
* documentation/users-guide/source/reference.rst
(``assert-instance?``, ``assert-not-instance?``): Document.
(``check-instance?``): Correct terminology: type, not class.
* …
=> assert-instance?, assert-not-instance?

run.dylan
This increases duplication of calling make to create the result,
but it allows for `execute-component` to do something different to
create results unlike the current arrangement.
This change lays the ground work for an improvement in how
benchmarks are implemented.
* run.dylan
(`maybe-execute-component`): Update to create result in skipped
case, otherwise, use result returned from executing the component.
(`execute-component`): Change return value to be a result and
create and return the result.
=> Let execute-component return <component-result>.

assertions.dylan, tests/testworks-test-suite.dylan
Some minor clean up. Hopefully this helps us move in the direction of sharing more code between the `do-check-*` functions and subsequently being able to export the helper function to let libraries write their own assertions.
This would be useful for the `dfmc-testing` tests for the `dfmc-typist` as this would let it provide more useful feedback when a `typist-inference` test fails.
=> Cleanup do-check-* functions

reports.dylan
* reports.dylan
(log-report-function): Wrap the stream in an indenting stream.
When recursing on subresults, indent the stream by 2 spaces.
=> [log report] Indent based on suite/test hierarchy.

specs/function-specs.dylan
Problem reported by peterhull on IRC. Tested by adding appropriate
"define generic" forms to the system:date module, which fixed the
associated failures in the system-test-suite-app.
(I'm a little baffled by how this went unnoticed for so long so I hope I'm not being a complete dunderhead here.)
=> Fix generic function argument type check by swapping the subtype? args.

command-line.dylan, documentation/users-guide/source/reference.rst, library.dylan, run.dylan, tests/test-command-line.dylan, tests/testworks-test-suite-library.dylan
Most of the original removal was done in 281d721.
Fixes #88.
There are probably a lot of callers of "define test" etc in OD that use this obsolete keyword...
=> A few minor enhancements and bug fixes

assertions.dylan, reports.dylan
With failures (mostly the same as before):
```
testworks-test-suite-app FAILED in 0.102848 seconds:
Ran 10 suites: 6 passed (60.000004%), 4 failed, 0 skipped, 0 not implemented, 0 crashed
Ran 37 tests: 35 passed (94.594592%), 2 failed, 0 skipped, 0 not implemented, 0 crashed
Ran 1 benchmark: 1 passed (100.00000%)
Ran 1455 checks: 1453 passed (99.862552%), 2 failed, 0 skipped, 0 not implemented, 0 crashed
```
Complete success:
```
testworks-test-suite-app PASSED in 0.107978 seconds:
Ran 10 suites: 10 passed (100.00000%)
Ran 37 tests: 37 passed (100.00000%)
Ran 1 benchmark: 1 passed (100.00000%)
Ran 1455 checks: 1455 passed (100.00000%)
```
=> Improvements to testworks output

components.dylan, library.dylan
It was only used for the inc! macro, which isn't very important.  I'm
not sure, but I may have started out using uncommon-dylan more than
that and then pared it down to just inc! without thinking to remove
it.
=> Remove use of uncommon-dylan, which is not an opendylan submodule.

command-line.dylan, registry/generic/testworks-run, run/library.dylan, run/testworks-run.dylan, run/testworks-run.lid
So that it is no longer necessary to build a test-runner application for each test suite library, these changes add a --load option to the testworks run-test-application function, and provide a standalone application that can be used to load test suite libraries and run them.
=> Implement a standalone testworks-run app

benchmark.dylan, command-line.dylan, library.dylan, reports.dylan, results.dylan, run.dylan
This pull request adds support for repeatedly executing code to be benchmarks for a specified number of iterations, and performing basic statistical analysis on the per-iteration results.
=> Add a benchmark-repeat macro and benchmark analysis

library.dylan, tests/specification.dylan
Export <metered-result> from %testworks, for the test suite.
Fixes one test failure.
=> Update spec to match result-time function

assertions.dylan
Adding "(from expression ...)" is redundant with the auto-generated test name.
Changed from this:
```
"{1:2}" = to-string(table, #f) failed ["{1:2}" (from expression "\"{1:2}\"") and "{1: 2}" (from expression "to-string(table, #f)") are not =.  sizes differ (5 and 6), element 3 is the first non-matching element]
```
to this:
```
"{1:2}" = to-string(table, #f): ["{1:2}" and "{1: 2}" are not =.  sizes differ (5 and 6), element 3 is the first non-matching element]
```
=> Reduce verbosity/redundancy in assert-equal failures

benchmark.dylan
To match an earlier commit that changed the other methods on this function.
testworks-test-suite-app passes
=> [testworks] Downcase result-type-name values

report/readers.dylan, reports.dylan
With this the json reports for dylan-test-suite can be read by testworks-report.
=> [testworks reports] fix write/read of crashed tests

command-line.dylan, library.dylan, report/initialize.dylan, report/readers.dylan, reports.dylan
It's currently broken and redundant with the "xml" and "json" formats in any
case.
=> Remove the "log" report format

documentation/users-guide/source/reference.rst, specs.dylan, tests/specification.dylan
=> Allow specs to specify expected-to-fail-reason

documentation/users-guide/source/usage.rst
The 'define benchmark' should've been 'define suite'.
=> Fix "Quick Start" section bugs, clarify run-test-application

components.dylan, documentation/users-guide/source/reference.rst, documentation/users-guide/source/usage.rst, run.dylan, tests/test-command-line.dylan, tests/testworks-test-suite.dylan
Rename expected-to-fail? to expected-to-fail-test
This option is easy to misuse, like this:
`expected-to-fail?: $os-name == #"win32"`
so I tried to make it clearer that the value should always be a function.
=> Rename expected-to-fail? to expected-to-fail-test

documentation/source/reference.rst, run.dylan, tests/testworks-test-suite-library.dylan, tests/testworks-test-suite.dylan
I sometimes name tests "test-foo/subtest1", "test-foo/subtest2", and since the test temp directory is named after the test this causes an error.
=> test-temp-directory: Replace / and \ with _

.github/workflows/build-and-test.yml, .github/workflows/build-docs.yml
Build documentation and upload it to Github Pages.
Some updates has been needed:
- Update to actions/checkout@v3 since node v12 is deprecated.  (see https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/)
- Update action install-opendylan@v3 with compiler version 2023.1 to build in macos
- Update path of dylan-compiler
=> Add workflow to build documentation

.github/workflows/build-and-test.yml
- Use dylan-tool to build the tests.
- Removing checkout recursive since there are no submodules.
=> Build tests using 'dylan-tool'

assertions.dylan, benchmark.dylan, coloring.dylan, command-line.dylan, components.dylan, documentation/source/reference.rst, documentation/source/usage.rst, dylan-package.json, library.dylan, report/readers.dylan, report/reports.dylan, reports.dylan, results.dylan, run.dylan, tests/specification.dylan, tests/test-command-line.dylan, tests/testworks-test-suite.dylan, utils.dylan
For example, the failures report now looks like this:
```
$ _build/bin/testworks-test-suite-app --progress none
FAILED: testworks-test-suite-app
FAILED: test-assert-equal-output
FAILED: b
1 (from expression "1") is not an instance of {class <string>}.
FAILED: f
no condition signaled
CRASHED: g
Error evaluating assertion expression: foo
FAILED: list, same size, different elements
want: #("a", "b", "c", "d")
got:  #("a", "b", "x", "d")
detail: element 2 is the first mismatch
...
Ran 1289 assertions
Ran 54 tests and 2 benchmarks: 1 failed and 4 expected failures
FAILED in 0.312805 seconds
```
=> Improve --progress and --report output

assertions.dylan, documentation/source/reference.rst, documentation/source/usage.rst, library.dylan, tests/testworks-test-suite.dylan
These macros don't terminate the test, so in that respect they're similar to the `check-*` macros, but their signatures are like the `assert-*` macros, in which the assertion description is optional and if not supplied is auto-generated from the arguments.
See discussion in https://github.com/dylan-lang/testworks/issues/86
=> Add expect-* macros to match the assert-* macros

command-line.dylan
=> Fix `--debug crashes`, broken in recent commit

documentation/source/usage.rst
A link to reference document points to a page (Assertion) that does not exists.
=> Doc: Link to reference document (fix #167)

assertions.dylan, library.dylan, tests/testworks-test-suite.dylan
And for symmetry with assert-true/false. 
Editorializing a bit, I think we really only need the expect/assert and expect/assert-equal variants, but this is where we're at so I'm not gonna fight it.
=> Add expect-true macro for symmetry with expect-false

.github/workflows/build-docs.yml, .gitignore, documentation/source/conf.py, documentation/source/reference.rst, documentation/source/usage.rst
- Integrate with `dylan-tool`
- Update CI of docs
=> Update testworks documentation CI

command-line.dylan, components.dylan, library.dylan, run.dylan, tests/specification.dylan, tests/test-command-line.dylan, tests/testworks-test-suite.dylan
This changes the way the runner works a little bit. Instead of checking tags and looking for suite setup/cleanup during the test run everything is computed in advance and the exact set of components that will be executed based on command-line args is stored in the runner-components slot. If a suite is in that set, then its setup/cleanup need to be run. This also meant that runner-tags and runner-skip were no longer needed.
Fixes #148
=> Run suite setup/cleanup when --test is used

command-line.dylan, dylan-package.json, library.dylan, utils.dylan
There are trivial workarounds for use of the strings library so remove the dependency to avoid potential version conflicts given that almost every other library uses Testworks as a dev dependency.
Also switched the sphinx-extensions dev dependency from a specific version to latest, for the same reason.
Fixes #172
Related to https://github.com/dylan-lang/deft/issues/43
=> Remove dependence on "strings" library, use latest sphinx-extensions

assertions.dylan
The new output looks like this:
```
FAILED: test-foo
FAILED: concatenate("a", "b") is an instance of <integer>
"ab", from expression concatenate("a", "b"), is not an instance of {class <integer>}.
FAILED: instance?(concatenate("a", "b"), <integer>)
expression instance?(concatenate("a", "b"), <integer>) is false.
```
The `{class <integer>}` output, rather than just `<integer>` is due to the way macro expansion is done for `?"type"` and I'm not going to worry about it for now.
Fixes #195
=> Minor improvement to assertion failure output

.github/workflows/build-and-test.yml, tests/testworks-test-suite.dylan
See the red rectangle.
Also use `--report-file`, which is better because it allows default progress output to be written to the workflow logs.
=> Fix build-and-test.yml

components.dylan, documentation/source/reference.rst, library.dylan
=> Export and document test creation API
